openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:5000
paths:
  /v1/auth/login:
    post:
      tags:
        - "Auth"
      summary: "Login API"
      operationId: "ctrlValue.postLogin"
      requestBody:
        description: user Login
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  refreshtoken:
                    type: string
                  accesstoken:
                    type: string
        '400':
          description: Bad Request