openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:5000
paths:
  /v1/auth/login:
    post:
      tags:
        - "Auth"
      summary: "Login API"
      operationId: "ctrlValue.postLogin"
      requestBody:
        description: user Login
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: rkr1029@gmail.com
                password:
                  type: string
                  example: A3gjklz!
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  refreshtoken:
                    type: string
                  accesstoken:
                    type: string
        '400':
          description: Bad Request
  /v1/auth/register:
    post:
      tags:
        - "Auth"
      summary: "Register API"
      operationId: "ctrlValue.postRegister"
      requestBody:
        description: User Register
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Register Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid Input
  /v1/auth/logout:
    post:
      tags:
        - "Auth"
      summary: "Logout API"
      operationId: "ctrlValue.postLogout"
      requestBody:
        description: User Logout
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Failure Logout