openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:5000
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
paths:
  /v1/user:
    get:
      tags:
        - "User"
      summary: "User Info"
      operationId: "ctrlValue.GetUserInfo"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
